import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerZIP } from '@electron-forge/maker-zip';
import { VitePlugin } from '@electron-forge/plugin-vite';
import { FusesPlugin } from '@electron-forge/plugin-fuses';
import { FuseV1Options, FuseVersion } from '@electron/fuses';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const BIN_DIR = path.join(__dirname, 'bin');
const ICON = path.join(__dirname, 'assets', 'icon');

/**
 * Build the Go capture helper into `bin/readerctl` so it can be shipped as an
 * extra resource at `Contents/Resources/bin/readerctl` (SPEC 10.1).
 */
function buildReaderctl() {
  fs.mkdirSync(BIN_DIR, { recursive: true });
  execFileSync('go', ['build', '-trimpath', '-o', path.join(BIN_DIR, 'readerctl'), '.'], {
    cwd: path.join(__dirname, 'readerctl'),
    stdio: 'inherit',
    env: { ...process.env, CGO_ENABLED: '0' },
  });
}

function buildIcon() {
  execFileSync(process.execPath, [path.join(__dirname, 'scripts', 'make-icon.mjs')], {
    stdio: 'inherit',
  });
}

/**
 * Signing identity, if one is configured. Set `FR_SIGN_IDENTITY` to a Developer
 * ID Application certificate to produce a build that Gatekeeper accepts without
 * the recipient overriding anything; leave it unset for a local ad-hoc build.
 */
const SIGN_IDENTITY = process.env.FR_SIGN_IDENTITY;
const NOTARIZE =
  process.env.APPLE_ID && process.env.APPLE_PASSWORD && process.env.APPLE_TEAM_ID
    ? {
        appleId: process.env.APPLE_ID,
        appleIdPassword: process.env.APPLE_PASSWORD,
        teamId: process.env.APPLE_TEAM_ID,
      }
    : undefined;

/**
 * Re-apply the ad-hoc signature after packaging.
 *
 * The fuses plugin ad-hoc signs at `packageAfterCopy`, but Packager rewrites
 * `Info.plist` afterwards — renaming the bundle and applying `extendInfo`. That
 * invalidates the signature it just made: the bundle ends up claiming
 * `com.github.Electron` with an unbound plist, and macOS reports it not as
 * unsigned but as *damaged*, which no amount of right-click-Open will get past.
 * Signing again here, last, binds the signature to the final bundle.
 *
 * A real identity does not need this: `osxSign` runs after Packager is done.
 */
function resignAdHoc(appPath: string) {
  execFileSync('codesign', ['--force', '--deep', '--sign', '-', appPath], { stdio: 'inherit' });
  execFileSync('codesign', ['--verify', '--deep', '--strict', appPath], { stdio: 'inherit' });
}

const config: ForgeConfig = {
  packagerConfig: {
    name: 'Focus Reader',
    appBundleId: 'com.focusreader.app',
    asar: true,
    icon: ICON, // Packager appends `.icns`; generated by scripts/make-icon.mjs.
    appCategoryType: 'public.app-category.productivity',
    ...(SIGN_IDENTITY
      ? {
          osxSign: {
            identity: SIGN_IDENTITY,
            optionsForFile: () => ({
              entitlements: path.join(__dirname, 'assets', 'entitlements.plist'),
            }),
          },
          ...(NOTARIZE ? { osxNotarize: NOTARIZE } : {}),
        }
      : {}),
    // The Go helper lives outside the asar so hooks can exec it directly.
    extraResource: [BIN_DIR],
    extendInfo: {
      // Menu-bar-first: no Dock icon, no window at launch (SPEC 4.1).
      LSUIElement: true,
      CFBundleDocumentTypes: [
        {
          CFBundleTypeName: 'Markdown or plain text document',
          CFBundleTypeRole: 'Viewer',
          LSHandlerRank: 'Alternate',
          LSItemContentTypes: ['net.daringfireball.markdown', 'public.plain-text'],
        },
      ],
    },
  },
  rebuildConfig: {},
  makers: [new MakerZIP({}, ['darwin'])],
  hooks: {
    generateAssets: async () => {
      buildReaderctl();
      buildIcon();
    },
    postPackage: async (_config, result) => {
      if (result.platform !== 'darwin' || SIGN_IDENTITY) return;
      for (const dir of result.outputPaths) {
        resignAdHoc(path.join(dir, 'Focus Reader.app'));
      }
    },
  },
  plugins: [
    new VitePlugin({
      build: [
        { entry: 'src/main/index.ts', config: 'vite.main.config.ts', target: 'main' },
        { entry: 'src/preload/index.ts', config: 'vite.preload.config.ts', target: 'preload' },
      ],
      renderer: [
        { name: 'overlay', config: 'vite.overlay.config.ts' },
        { name: 'library', config: 'vite.library.config.ts' },
      ],
    }),
    new FusesPlugin({
      version: FuseVersion.V1,
      [FuseV1Options.RunAsNode]: false,
      [FuseV1Options.EnableCookieEncryption]: true,
      [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
      [FuseV1Options.EnableNodeCliInspectArguments]: false,
      [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
      [FuseV1Options.OnlyLoadAppFromAsar]: true,
    }),
  ],
};

export default config;
