/**
 * Public half of the update-signing keypair, generated by
 * scripts/make-update-key.mjs. Safe to publish — it can only verify.
 *
 * An update manifest that does not carry a valid signature under this key is
 * discarded before its contents are read, so a compromised release host cannot
 * push code to anyone.
 */
export const UPDATE_PUBLIC_KEY_SPKI_BASE64 =
  'MCowBQYDK2VwAyEA99gRAxz2FZ8TXrVrawZwH7tx4JZfrLSp01Mvj/b9rYI=';
